### PR TITLE
Resolved the remarks.map error

### PR DESCRIPTION
**Pull request by Ishan2601**
Error resolved.
Please check code.

### CODE REVIEW

**Review by sarthakkundra — CHANGES_REQUESTED** [review]
Hi Ishan, 
This seems to be incorrect as you've replaced a POST request with a GET request and since adding a remark basically means we have to save data into our database, then we need to use POST request. By doing this we'll essentially be getting the same remarks over and over again and not saving anything new in the DB.

**Comment by Ishan2601** [comment]
Hi Sarthak, 
I have not replaced the POST request with a GET request. I have just added a GET request after the POST request to get the updated remarks list. Kindly correct me if I am wrong so that I will try some different solution.

**Comment by sarthakkundra** [comment]
@Ishan2601 okay yeah that can also be one work around. Good work!

**Comment by Ishan2601** [comment]
Thanks a lot! @sarthakkundra

**Pull request merged**
